# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-15 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_videos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='videos',
            new_name='Video',
        ),
    ]
