# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-15 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180315_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='urls',
            field=models.CharField(max_length=300),
        ),
    ]
