# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-16 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180316_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='ybUrl',
            field=models.CharField(blank=True, default='https://www.youtube.com/embed/', max_length=200),
        ),
    ]
