# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-16 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('pseudo', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
