# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_membre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='fullname',
        ),
        migrations.AddField(
            model_name='membre',
            name='nomcomplet',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='membre',
            name='poste',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='membre',
            name='pseudo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
