# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180316_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=250)),
                ('logo', models.ImageField(upload_to='photos/')),
                ('url', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
