# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-18 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_partenaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(max_length=250)),
                ('adresse', models.CharField(max_length=500)),
                ('contenu', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
            ],
        ),
        migrations.DeleteModel(
            name='Membre',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
