# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180318_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='logo',
            field=models.ImageField(upload_to='logo/'),
        ),
    ]
