# Generated by Django 2.0 on 2018-03-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180322_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=250)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('url', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
