# Generated by Django 2.0 on 2018-03-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_sponsor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
