# Generated by Django 2.0.3 on 2018-03-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to='Photo_Article/'),
        ),
    ]
